'reinit'
'enable print F:\16303003.gmf'
'sdfopen F:\data\NCEP\uwnd.mon.mean.nc'
'sdfopen F:\data\NCEP\vwnd.mon.mean.nc'
*'colormap MPL_rainbow'
'set gxout vector'
'display uwnd.1;vwnd.2;mag(uwnd.1,vwnd.2)'
'print'
'c'
'set gxout barb'
'display uwnd.1;vwnd.2;mag(uwnd.1,vwnd.2)'
'print'
'c'
'set gxout stream'
'display uwnd.1;vwnd.2;mag(uwnd.1,vwnd.2)'
'print'
'c'
'quit'
