'enable print F:\data\compare.gmf'
'open F:\data\grads\uwnd_part.ctl'
'd u'
'print'
'clear'
'open F:\data\grads\uwnd.levs.monthly.ERAINT.ctl'
'set dfile 2'
'set lat -30 40'
'set lon 40 180'
'set lev 850'
'set t 255'
'q ctlinfo'
'd u'
'print'
'clear'
'd u.1'
'd u.2'
'print'
'clear'
'disable print'
'quit'