'reinit'
'enable print F:\week6.3.16303003.gmf'
'sdfopen F:\data\grads\uwnd.levs.monthly.ERAINT.nc'
'set lon 40 180'
'set lat 15 60'
'set lev 850'
'set t 7'
'set gxout contour'
'set grads off'
'set xlint 20'
'set ylint 15'
'draw ylab latitude'
'd u'
'draw title U-wind at 850 hPa JUL'
'draw xlab longitude'
'print'
'c'
'disable print'
'quit'
*