'reinit'
'enable print F:\scripts\grads\week3\2.16303003.gmf'
'sdfopen F:\data\grads\uwnd.levs.monthly.ERAINT.nc'
'sdfopen F:\data\grads\vwnd.levs.monthly.ERAINT.nc'
**************
'set dfile 1'
'set time may2010'
'set lev 850'
'd u'
'print'
'c'
'set dfile 2'
'set time may2010'
'set lev 850'
'd v'
'print'
'c'
'disable print'
'quit'
*