'reinit'
'enable print F:\4.1630303.gmf'
'sdfopen F:\data\grads\vwnd.levs.monthly.ERAINT.nc'
'set lat 20'
'set lon 115'
'set lev 850'
'set time jan2000 dec2000'
'set gxout bar'
'set bargap 20'
'set ccolor 2'
'set barbase 0'
'set baropts filled'
'd v'
'print'
'c'
'set gxout line'
'set ccolor 4'
'set cthick 8'
'set cstyle 3'
'set cmark 3'
'set digsiz 0.15'
'd v'
'print'
'disable print'
'quit'
